### ISSUE TITLE
I need help. [Resolved]

### ISSUE THREAD

**Issue by bknhnz** [kekko9994/Gota-Private-Server#1]
The error code always appears when I try to join server.
What should I do?
![error](https://user-images.githubusercontent.com/63880676/79615265-f4966180-8134-11ea-91e7-971337cf5dde.png)

**Comment by kekko9994** [comment]
reinstall your nodejs, but not with the latest version, this is the version do you need: https://mega.nz/file/FVVwXapJ#oWTAaSFzOGZ8elDZmdf8l8HQkq9MbNpm8iXRm2A0hQc

**Comment by bknhnz** [comment]
thx!

**Comment by kekko9994** [comment]
One question: You like my gota.io private server?

**Comment by bknhnz** [comment]
yes
